/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_pwsafe_lib_crypto_SHA256Pws */

#ifndef INCLUDE_org_pwsafe_lib_crypto_SHA256Pws
#define INCLUDE_org_pwsafe_lib_crypto_SHA256Pws
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_pwsafe_lib_crypto_SHA256Pws
 * Method:    doDigestN
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_pwsafe_lib_crypto_SHA256Pws_digestNNative
  (JNIEnv* env, jclass clazz, jbyteArray inbuf, jint iter);

#ifdef __cplusplus
}
#endif
#endif
