name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Checkout Yubikit-android
      uses: actions/checkout@v4
      with:
        repository: Yubico/yubikit-android
        ref: d1f58c0e9b7de5e8a9e8bed5411ee5e5654d655a
        path: yubikit

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Build Yubikit-android
      run: ./gradlew build publishToMavenLocal
      working-directory: ./yubikit

    - name: Build with Gradle
      run: ./gradlew build

    - name: Archive results
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: archive
        if-no-files-found: ignore
        path: |
          build/reports/dependency-verification/
          */build/reports/
          */build/intermediates/lint_intermediate_text_report/
