name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Build with Gradle
      run: ./gradlew build

    - name: Archive results
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: archive
        if-no-files-found: ignore
        path: |
          build/reports/dependency-verification/
          */build/reports/
          */build/intermediates/lint_intermediate_text_report/
